secrets:
  hf_token:
    file: ./hf_token_secret

services:
  ray_and_vllm:
    build: ../containers/vllm_server
    privileged: true 
    network_mode: "host"
    container_name: ray_and_vllm
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    shm_size: 10.24gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    secrets:
      - hf_token
    environment:
      - MN_IF_NAME=enp1s0f0np0
      - VLLM_HOST_IP=169.254.138.85
      - UCX_NET_DEVICES=enp1s0f0np0
      - NCCL_SOCKET_IFNAME=enp1s0f0np0
      - OMPI_MCA_btl_tcp_if_include=enp1s0f0np0
      - GLOO_SOCKET_IFNAME=enp1s0f0np0
      - TP_SOCKET_IFNAME=enp1s0f0np0
      - RAY_memory_monitor_refresh_ms=0
      - MASTER_ADDR=169.254.138.85
      - RAY_MODE=head
  openui:
    privileged: true
    network_mode: "host"
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ~/open-webui:/app/backend/data
  openterminal:
    privileged: true
    network_mode: "host"
    container_name: openterminal
    image: ghcr.io/open-webui/open-terminal
    volumes:
      - ~/:/open-terminal
    environment:
      - OPEN_TERMINAL_API_KEY=openterminalkey
